// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCizYGKhfiMKCTBVDjDNb_X0tHgikWhNRU',
    appId: '1:1049239223926:web:49f8db592e06f8c2e22957',
    messagingSenderId: '1049239223926',
    projectId: 'smart-travel-companion-1d287',
    authDomain: 'smart-travel-companion-1d287.firebaseapp.com',
    storageBucket: 'smart-travel-companion-1d287.firebasestorage.app',
    measurementId: 'G-T0HV8WQ14K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwVwJVoQerkXK0AvrIiEQX6zG2HnH4gIc',
    appId: '1:1049239223926:android:fc72c00c4d392822e22957',
    messagingSenderId: '1049239223926',
    projectId: 'smart-travel-companion-1d287',
    storageBucket: 'smart-travel-companion-1d287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoCUb3fdKwZwWXNefsU6n2SSnpJGPYqo0',
    appId: '1:1049239223926:ios:dd93dcd50831415be22957',
    messagingSenderId: '1049239223926',
    projectId: 'smart-travel-companion-1d287',
    storageBucket: 'smart-travel-companion-1d287.firebasestorage.app',
    iosClientId: '1049239223926-vn733j3t4912sokklanf1ngjdcj1162p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoCUb3fdKwZwWXNefsU6n2SSnpJGPYqo0',
    appId: '1:1049239223926:ios:dd93dcd50831415be22957',
    messagingSenderId: '1049239223926',
    projectId: 'smart-travel-companion-1d287',
    storageBucket: 'smart-travel-companion-1d287.firebasestorage.app',
    iosClientId: '1049239223926-vn733j3t4912sokklanf1ngjdcj1162p.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCizYGKhfiMKCTBVDjDNb_X0tHgikWhNRU',
    appId: '1:1049239223926:web:d0190dfe9960cd3de22957',
    messagingSenderId: '1049239223926',
    projectId: 'smart-travel-companion-1d287',
    authDomain: 'smart-travel-companion-1d287.firebaseapp.com',
    storageBucket: 'smart-travel-companion-1d287.firebasestorage.app',
    measurementId: 'G-SKD6E0CV2C',
  );
}
